/**
 * @fileoverview Migration — Add pista_chat_logs table.
 *
 * Adds the P.I.S.T.A. conversation history ledger to an existing coolkonyha.db.
 * Chat messages are bound to an order context (order_id) when a specific order
 * is open, or NULL for global Dashboard conversations.
 *
 * Safe to run multiple times (uses CREATE TABLE IF NOT EXISTS).
 *
 * @see docs/assistant_team/pista-agent.md — Chat history architecture decision
 * @see server/agent.js — DBRobot.saveChatMessage / DBRobot.getChatHistory
 */

import sqlite3 from 'sqlite3';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DB_PATH = path.resolve(__dirname, '../coolkonyha.db');

// -----------------------------------------------------------------
// Role values:
//   'ck'    — message sent by CK (the user)
//   'pista' — message/proposal generated by P.I.S.T.A.
//
// order_id:
//   NOT NULL → conversation was done in context of a specific order
//   NULL     → Dashboard-level conversation (global context)
// -----------------------------------------------------------------
const CREATE_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS pista_chat_logs (
    log_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id     INTEGER,
    role         TEXT    NOT NULL CHECK(role IN ('ck', 'pista')),
    message      TEXT    NOT NULL,
    proposal     TEXT,
    created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);
`;

// Index speeds up the most common query: load history for a given order (or dashboard)
const CREATE_INDEX_SQL = `
CREATE INDEX IF NOT EXISTS idx_pista_chat_logs_order_id
ON pista_chat_logs(order_id, created_at);
`;

const db = new sqlite3.Database(DB_PATH, (err) => {
    if (err) {
        console.error('Error opening database:', err.message);
        process.exit(1);
    }
    console.log('Connected to coolkonyha.db');
});

db.serialize(() => {
    db.run('PRAGMA foreign_keys = ON;');

    db.run(CREATE_TABLE_SQL, (err) => {
        if (err) {
            console.error('Migration failed:', err.message);
            process.exit(1);
        }
        console.log('✅ pista_chat_logs table created (or already existed).');
    });

    db.run(CREATE_INDEX_SQL, (err) => {
        if (err) {
            console.error('Index creation failed:', err.message);
        } else {
            console.log('✅ idx_pista_chat_logs_order_id index created (or already existed).');
        }
    });

    db.close((err) => {
        if (err) console.error('Error closing database:', err.message);
        else console.log('✅ Migration complete. Database connection closed.');
    });
});
