-- Canonical schema for coolkonyha.db.
--
-- Generated by introspecting the real production database's sqlite_master
-- table (2026-09-04, as part of docs/.notes/future-ideas.md i-2 — retargeting
-- the test suite to exercise real code against a real schema instead of a
-- hand-maintained, drifted copy). This file is byte-accurate to what
-- production actually has, not an aspirational/target schema — notably,
-- `sender_rules` (documented in docs/architecture/database-schema.md) is
-- intentionally NOT included here because it does not exist in production
-- yet; server/robots/robot-pista-db.js already handles its absence
-- gracefully (returns [] instead of throwing).
--
-- Consumed by server/db.js when DB_PATH resolves to ':memory:' (test runs).
-- If you add/alter a table in production, regenerate this file the same way
-- rather than hand-editing it, to avoid it drifting again.

PRAGMA foreign_keys = ON;

-- 1. Master Data
CREATE TABLE customers (
    cust_id INTEGER PRIMARY KEY AUTOINCREMENT,
    cust_name TEXT NOT NULL,
    cust_contact TEXT,
    cust_email TEXT NOT NULL,
    cust_email2 TEXT,
    cust_phone TEXT,
    cust_web TEXT,
    cust_note TEXT,
    cust_reg_date DATE DEFAULT CURRENT_DATE
, notes TEXT, logo_path TEXT);

CREATE TABLE product_suppliers (
    prod_supp_id INTEGER PRIMARY KEY AUTOINCREMENT,
    prod_supp_co TEXT NOT NULL,
    prod_supp_name TEXT,
    prod_supp_email TEXT,
    prod_supp_phone TEXT,
    prod_supp_web TEXT,
    prod_supp_note TEXT,
    prod_supp_reg_date DATE DEFAULT CURRENT_DATE
, notes TEXT, logo_path TEXT);

CREATE TABLE products (
    prod_id INTEGER PRIMARY KEY AUTOINCREMENT,
    prod_name TEXT NOT NULL,
    prod_type TEXT,
    prod_size TEXT,
    prod_note TEXT,
    prod_reg_date DATE DEFAULT CURRENT_DATE,
    prod_supp_id INTEGER,
    unit_price NUMERIC(10,2), notes TEXT, image_path TEXT,
    FOREIGN KEY (prod_supp_id) REFERENCES product_suppliers(prod_supp_id)
);

-- 2. Orders Domain
CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY AUTOINCREMENT,
    cust_id INTEGER NOT NULL,
    order_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    total_amount NUMERIC(12,2),
    current_status TEXT,
    current_status_update DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_event TEXT,
    currency TEXT DEFAULT 'HUF', notes TEXT, order_code TEXT,
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
);

CREATE UNIQUE INDEX idx_orders_code ON orders(order_code);

CREATE TABLE order_items (
    order_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL,
    prod_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
);

CREATE TABLE order_status_history (
    history_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL,
    status TEXT NOT NULL,
    update_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_event TEXT,
    performed_by TEXT,
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

CREATE TABLE "order_status_workflow" (
    status_id INTEGER PRIMARY KEY AUTOINCREMENT,
    status_key TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    description TEXT,
    is_skippable BOOLEAN DEFAULT FALSE,
    status_color TEXT
);

INSERT INTO order_status_workflow (status_key, display_name, description, is_skippable, status_color) VALUES
('NEW', 'New', 'New inquiry received', 0, '#F1F3F4'),
('OFFER_SENT', 'Offer Sent', 'Price offer sent to customer', 0, '#FFF9C4'),
('ORDER_CONFIRMED', 'Order Confirmed', 'Customer signed the order', 0, '#FFD54F'),
('PURCHASE', 'Purchase', 'Ordering materials from suppliers', 1, '#FB8C00'),
('READY_FOR_DELIVERY', 'Ready for Delivery', 'Production finished, ready to ship', 0, '#E1F5FE'),
('DELIVERY', 'Delivery', 'In transit to customer site', 0, '#90CAF9'),
('DELIVERED', 'Delivered', 'Installation finished and accepted', 0, '#3F51B5'),
('INVOICED', 'Invoiced', 'Final invoice sent', 0, '#A5D6A7'),
('CLOSED', 'Closed', 'Order cycle completed', 0, '#2E7D32'),
('CANCELLED', 'Cancelled', 'Order was canceled', 0, '#C62828');

-- 3. Maintenance Domain
CREATE TABLE maintenance_cases (
        case_id                  INTEGER PRIMARY KEY AUTOINCREMENT,
        case_code                TEXT UNIQUE,
        cust_id                  INTEGER NOT NULL,
        case_date                DATETIME DEFAULT CURRENT_TIMESTAMP,
        description              TEXT,
        current_status           TEXT NOT NULL DEFAULT 'NEW',
        current_status_update    DATETIME DEFAULT CURRENT_TIMESTAMP,
        update_event             TEXT,
        notes                    TEXT,
        FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
      );

CREATE TABLE maintenance_items (
        item_id     INTEGER PRIMARY KEY AUTOINCREMENT,
        case_id     INTEGER NOT NULL,
        prod_id     INTEGER NOT NULL,
        quantity    INTEGER NOT NULL DEFAULT 1,
        issue_note  TEXT,
        FOREIGN KEY (case_id) REFERENCES maintenance_cases(case_id),
        FOREIGN KEY (prod_id) REFERENCES products(prod_id)
      );

CREATE TABLE maintenance_status_history (
        history_id   INTEGER PRIMARY KEY AUTOINCREMENT,
        case_id      INTEGER NOT NULL,
        status       TEXT NOT NULL,
        update_date  DATETIME DEFAULT CURRENT_TIMESTAMP,
        update_event TEXT,
        performed_by TEXT,
        FOREIGN KEY (case_id) REFERENCES maintenance_cases(case_id)
      );

CREATE TABLE maintenance_status_workflow (
        status_id    INTEGER PRIMARY KEY AUTOINCREMENT,
        status_key   TEXT UNIQUE NOT NULL,
        display_name TEXT NOT NULL,
        description  TEXT,
        is_skippable BOOLEAN DEFAULT FALSE,
        status_color TEXT
      );

INSERT INTO maintenance_status_workflow (status_key, display_name, description, is_skippable, status_color) VALUES
('NEW', 'New', 'Maintenance request received', 0, '#F1F3F4'),
('DIAGNOSED', 'Diagnosed', 'Issue has been assessed', 0, '#FFF9C4'),
('PARTS_ORDERED', 'Parts Ordered', 'Replacement parts have been ordered', 1, '#FFD54F'),
('IN_REPAIR', 'In Repair', 'Active repair work in progress', 0, '#FB8C00'),
('TESTING', 'Testing', 'Repaired unit under quality testing', 1, '#E1F5FE'),
('READY', 'Ready', 'Repair complete, awaiting handover', 0, '#90CAF9'),
('INVOICED', 'Invoiced', 'Service invoice sent to customer', 0, '#A5D6A7'),
('CLOSED', 'Closed', 'Maintenance case fully completed', 0, '#2E7D32'),
('CANCELLED', 'Cancelled', 'Case was cancelled', 0, '#C62828');

-- 4. Email / P.I.S.T.A. Domain
CREATE TABLE processed_emails (
    email_id          INTEGER PRIMARY KEY AUTOINCREMENT,
    gmail_message_id  TEXT UNIQUE NOT NULL,
    thread_id         TEXT,
    email_date        DATETIME,
    direction         TEXT NOT NULL CHECK(direction IN ('received', 'sent')),
    from_address      TEXT,
    to_address        TEXT,
    subject           TEXT,
    ai_summary        TEXT,
    linked_order_id   INTEGER,
    status            TEXT NOT NULL DEFAULT 'pending'
                          CHECK(status IN ('pending', 'processed', 'failed', 'skipped')),
    processed_at      DATETIME,
    FOREIGN KEY (linked_order_id) REFERENCES orders(order_id)
);
